import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Bottombar from "@/components/Bottombar";
import SessionProvider from "@/providers/page";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={false}>
        <SessionProvider session={session}>
          <Navbar />
          <div className="block sm:hidden">
            <Bottombar />
          </div>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
